In [7]:
import numpy as np
data1 = np.array([1,4,1,2])
data2 = np.array([[1,44,2,5],[4,21,3,2]])
print(data1)
print(data1.shape)
print(data2)
print(data2.shape)

print(np.zeros([2,3]))
print(np.ones([2,3]))

print(data2[1,1])
data2[1,1] = 22
print(data2[1,1])

data3 = np.ones([2,3])
print(data3*2)

[1 4 1 2]
(4,)
[[ 1 44  2  5]
 [ 4 21  3  2]]
(2, 4)
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
21
22
[[2. 2. 2.]
 [2. 2. 2.]]
