In [ ]:
# tensorflow
# tensor 数据
# op operation
# graphs 数据操作过程（计算图）
# Session 执行核心，运算交互环境

In [ ]:
# tensorflow中数据要显示数值要用Session
import tensorflow as tf
data1 = tf.constant(2, dtype=tf.int32)
data2 = tf.Variable(10, name='var1')
'''
print(data1) #tensor 张量  shape 维度 dtype 类型
print(data2)
sess = tf.Session()
print(sess.run(data1))
init = tf.global_variables_initializer()
sess.run(init)
print(sess.run(data2))
sess.close()
'''
init = tf.global_variables_initializer()
sess = tf.Session()
with sess:
    sess.run(init)
    print(sess.run(data2))

In [ ]:
import tensorflow as tf
data1 = tf.constant(6)
data2 = tf.constant(2)
dataAdd = tf.add(data1, data2)
dataSub = tf.subtract(data1, data2)
dataMul = tf.multiply(data1, data2)
dataDiv = tf.divide(data1, data2)
with tf.Session() as sess:
    print(sess.run(dataAdd))
    print(sess.run(dataMul))
    print(sess.run(dataSub))
    print(sess.run(dataDiv))

In [ ]:
import tensorflow as tf
data1 = tf.constant(6)
data2 = tf.Variable(2)
dataAdd = tf.add(data1, data2)
dataCopy = tf.assign(data2, dataAdd) # dataAdd -> data2
dataSub = tf.subtract(data1, data2)
dataMul = tf.multiply(data1, data2)
dataDiv = tf.divide(data1, data2)
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(dataAdd))
    print(sess.run(dataMul))
    print(sess.run(dataSub))
    print(sess.run(dataDiv))
    print('sess.run(dataCopy):', sess.run(dataCopy)) # line5  data2 => 6 + 2
    print('daaCopy.eval():', dataCopy.eval()) #  data2 = dataAdd = data2 + data1 = 8 + 6
    print('tf.get_default_session().run(dataCopy)', tf.get_default_session().run(dataCopy)) # data2 = dataAdd = 14 + 6

In [ ]:
import tensorflow as tf
data1 = tf.placeholder(tf.float32)
data2 = tf.placeholder(tf.float32)
dataAdd = tf.add(data1, data2)
with tf.Session() as sess:
    print(sess.run(dataAdd, feed_dict={data1:6.2, data2:2.4}))

In [ ]:
# 矩阵
import tensorflow as tf
data1 = tf.constant([[4,2]])
data2 = tf.constant([[2], 
                     [3]])
data3 = tf.constant([[3,4]])
data4 = tf.constant([[2,4],
                    [1,4],
                    [5,2]])
print(data4.shape)
with tf.Session() as sess:
    print(sess.run(data4))
    print(sess.run(data4[1]))
    print(sess.run(data4[:,0]))
    print(sess.run(data4[0,0]))

matMul = tf.matmul(data1, data2);
matAdd = tf.add(data1, data3)
with tf.Session() as sess:
    print(sess.run(matMul))
    print(sess.run(matAdd))

In [8]:
import tensorflow as tf
mat0 = tf.constant([[0,0,0],[0,0,0]])
mat1 = tf.zeros([2,3])
mat2 = tf.ones([2,3])
mat3 = tf.fill([2,3], 12)
with tf.Session() as sess:
    print(sess.run(mat0))
    print(sess.run(mat1))
    print(sess.run(mat2))
    print(sess.run(mat3))

[[0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[12 12 12]
 [12 12 12]]


In [4]:
import tensorflow as tf
mat0 = tf.constant([[2],[3],[4]])
mat1 = tf.zeros_like(mat0)
mat3 = tf.linspace(0.0,2.0,10)
mat4 = tf.random_uniform([2,3], -1,2)
with tf.Session() as sess:
    print(sess.run(mat0))
    print(sess.run(mat1))
    print(sess.run(mat3))
    print(sess.run(mat4))

[[2]
 [3]
 [4]]
[[0]
 [0]
 [0]]
[0.         0.22222222 0.44444445 0.6666667  0.8888889  1.1111112
 1.3333334  1.5555556  1.7777778  2.        ]
[[ 0.44208932 -0.6575173   0.5579883 ]
 [ 0.5686989   1.9515848   0.739542  ]]
